name: Check Paclet

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-paclet:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install dependencies
        run: wolframscript -code 'PacletInstall["https://wolfr.am/11FhS453R"];PacletInstall["https://wolfr.am/11FhS4xyd"];'

      - name: Check paclet
        run: wolframscript -code 'PacletResource`CICD`CheckPaclet[]'

      - name: Build paclet
        run: wolframscript -code 'PacletResource`CICD`BuildPaclet[]'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/
          if-no-files-found: error
