name: Check Paclet

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  RESOURCE_PUBLISHER_TOKEN:    ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  RESOURCE_SYSTEM_BASE:        https://www.wolframcloud.com/obj/rhennigan/api/1.0
  TEST_CLOUD_ACCOUNT_PASSWORD: ${{ secrets.TEST_CLOUD_ACCOUNT_PASSWORD }}
  TEST_CLOUD_ACCOUNT_USER:     ${{ secrets.TEST_CLOUD_ACCOUNT_USER }}
  TEST_PUBLISHER_ID:           ${{ secrets.TEST_PUBLISHER_ID }}
  WOLFRAM_SYSTEM_ID:           Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}

jobs:
  check-paclet:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Check paclet
        run: wolframscript Scripts/CheckPaclet.wls
      
      - name: Upload stack data
        if: ${{ env.PACLET_STACK_HISTORY }}
        uses: actions/upload-artifact@v2
        with:
          name: check-paclet-stacks
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error

  test-paclet:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Test paclet
        run: wolframscript Scripts/TestPaclet.wls
      
      - name: Upload stack data
        if: ${{ env.PACLET_STACK_HISTORY }}
        uses: actions/upload-artifact@v2
        with:
          name: test-paclet-stacks
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error
      
      - name: Upload test results
        if: ${{ env.PACLET_TEST_RESULTS }}
        uses: actions/upload-artifact@v2
        with:
          name: test-paclet-results
          path: ${{ env.PACLET_TEST_RESULTS }}
          if-no-files-found: error