name: Check Paclet

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  WOLFRAM_SYSTEM_ID: Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}

jobs:
  check-paclet:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install dependencies
        run: wolframscript Scripts/InstallDependencies.wls

      - name: Check paclet
        run: wolframscript Scripts/CheckPaclet.wls

  test-paclet:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install dependencies
        run: wolframscript Scripts/InstallDependencies.wls

      - name: Test paclet
        run: wolframscript Scripts/TestPaclet.wls

      # TODO upload test results if there are failures (set env like build-paclet)