name: Check Paclet

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-paclet:
    runs-on: ubuntu-latest
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: rhennigan/check-paclet@main