name: Check Paclet

on:
  push:
    branches: ["main", "feature/0.3.0-updates"]
  pull_request:
    branches: ["main", "release/*"]
  workflow_dispatch:

env:
  WOLFRAM_SYSTEM_ID: Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}

jobs:
  check-paclet:
    name: Check Paclet
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install dependencies
        run: wolframscript Scripts/InstallDependencies.wls

      - name: Check paclet
        run: wolframscript Scripts/CheckPaclet.wls

  test-paclet:
    name: Test Paclet
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install dependencies
        run: wolframscript Scripts/InstallDependencies.wls

      - name: Test paclet
        run: wolframscript Scripts/TestPaclet.wls

      # TODO upload test results if there are failures (set env like build-paclet)