name: Release

on:
  workflow_dispatch:

  push:
    branches: ["release/*"]

env:
  RESOURCE_PUBLISHER_TOKEN:    ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  RESOURCE_SYSTEM_BASE:        https://www.wolframcloud.com/obj/rhennigan/api/1.0
  TEST_CLOUD_ACCOUNT_PASSWORD: ${{ secrets.TEST_CLOUD_ACCOUNT_PASSWORD }}
  TEST_CLOUD_ACCOUNT_USER:     ${{ secrets.TEST_CLOUD_ACCOUNT_USER }}
  TEST_PUBLISHER_ID:           ${{ secrets.TEST_PUBLISHER_ID }}
  WOLFRAM_SYSTEM_ID:           Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}

jobs:
  check-paclet:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Check paclet
        run: wolframscript Scripts/CheckPaclet.wls
      
      - name: Upload stack data
        if: ${{ env.PACLET_STACK_HISTORY }}
        uses: actions/upload-artifact@v2
        with:
          name: check-paclet-stacks
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error

  test-paclet:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Test paclet
        run: wolframscript Scripts/TestPaclet.wls
      
      - name: Upload stack data
        if: ${{ env.PACLET_STACK_HISTORY }}
        uses: actions/upload-artifact@v2
        with:
          name: test-paclet-stacks
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error
      
      - name: Upload test results
        if: ${{ env.PACLET_TEST_RESULTS }}
        uses: actions/upload-artifact@v2
        with:
          name: test-paclet-results
          path: ${{ env.PACLET_TEST_RESULTS }}
          if-no-files-found: error

  release-paclet:
    name: Release
    needs: [check-paclet, test-paclet]
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root

    timeout-minutes: 20
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build paclet
        run: wolframscript Scripts/BuildPaclet.wls
      
      - name: Upload stack data
        if: ${{ env.PACLET_STACK_HISTORY }}
        uses: actions/upload-artifact@v2
        with:
          name: release-paclet-stacks
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PacletBuildArtifact
          path: ${{ env.PACLET_BUILD_DIR }}
          if-no-files-found: error

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PACLET_RELEASE_TAG }}
          release_name: Release ${{ env.PACLET_RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.PACLET_PATH }}
          asset_name: ${{ env.PACLET_FILE }}
          asset_content_type: application/zip

  submit-paclet:
    name: Submit
    needs: [check-paclet, test-paclet]
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root

    timeout-minutes: 20
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Submit paclet
        run: wolframscript Scripts/SubmitPaclet.wls

      - name: Upload stack data
        if: ${{ env.PACLET_STACK_HISTORY }}
        uses: actions/upload-artifact@v2
        with:
          name: submit-paclet-stacks
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error