name: DeleteMe
on: 
  push: 
    branches:  [feature/test-summary-markdown]
  workflow_dispatch:

env:
  GITHUB_TOKEN:                ${{ secrets.GITHUB_TOKEN }}
  RESOURCE_PUBLISHER_TOKEN:    ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  RESOURCE_SYSTEM_BASE:        ${{ secrets.RESOURCE_SYSTEM_BASE }}
  TEST_CLOUD_ACCOUNT_PASSWORD: ${{ secrets.TEST_CLOUD_ACCOUNT_PASSWORD }}
  TEST_CLOUD_ACCOUNT_USER:     ${{ secrets.TEST_CLOUD_ACCOUNT_USER }}
  TEST_PUBLISHER_ID:           ${{ secrets.TEST_PUBLISHER_ID }}
  WOLFRAM_SYSTEM_ID:           Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}

jobs: 
  Test: 
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 10

    steps: 
      - name: Checkout
        id: checkout-code-step
        uses: actions/checkout@v2

      - name: Test paclet
        run: wolframscript Scripts/TestPaclet.wls
      
      - name: Upload stack data
        if: always() && env.PACLET_STACK_HISTORY
        uses: actions/upload-artifact@v2
        with:
          name: test-paclet-stacks-${{ env.WOLFRAM_SYSTEM_ID }}
          path: ${{ env.PACLET_STACK_HISTORY }}
          if-no-files-found: error
      
      - name: Upload test results
        if: always() && env.PACLET_TEST_RESULTS
        uses: actions/upload-artifact@v2
        with:
          name: test-paclet-results-${{ env.WOLFRAM_SYSTEM_ID }}
          path: ${{ env.PACLET_TEST_RESULTS }}
          if-no-files-found: error